FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Teamassistant (TAS)

REST Api is a complex API for managing entities of TAS and controlling workflows.

## Retrieving Lists
You can pass parameters for sorting and filtering.

### Additional parameters

    + Parameters
        + offset: 0 (number, optional) 
            - The number of items to skip before returning anything.
        + limit: 100 (number, optional) - (number, optional) 
            - The number of returned items.
        + filter: (string, optional) 
            - columnName<like>value
            - (<eq>|<nq>|<gt>|<lt>|<ge>|<le>|<like>|<nlike>)(<and|or>)
        + order: columnName
        + sort: asc|desc

## Login [/authenticate]

### Authenticate [POST]

+ Request Login (application/json)

        {
            "username": "yourId",
            "password": "yourPass",
            "grant_type": "password"
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "access_token": "a4ef8fd62eda54ade12fbb068da89092",
            "expires_in": 72000,
            "refreshTokenValidTo": "2016-12-03T15:36:06.115Z",
            "refresh_token": "y4gPzRDX52XSwA7sRb5Bfk1sMx2rlmBB6AE22AsaiQyK8woCdXqRCHFfA0LOGhA9",
            "tokenValidTo": "2015-12-05T11:36:06.115Z",
            "token_type": "Bearer"
        }

### Logout [POST /logout]

+ Request Login (application/json)

        {
        }

+ Response 200 (application/json; charset=utf-8)

        {
        }
        
## Task [/tasks]

### All Tasks [GET]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/tasks" },
            "completed_in": 0.21,
            "previous": null,
            "next": { "meta": { "href": "/tasks?offset=20&amp;limit=10"} },
            "items": [
                {
                    "itask_status": "A",
                    "iproc_id": 96152,
                    "ttask_id": 3217,
                    "itask_name": "proměnné pro čtení",
                    "itask_is_iproc_id": null,
                    "itask_description": null,
                    "itask_due_date_start": null,
                    "itask_due_date_finish": null,
                    "itask_actual_date_start": "2015-12-07T12:05:25.000Z",
                    "itask_actual_date_finish": null,
                    "itask_auto_start": "N",
                    "itask_user_id": 14827,
                    "itask_user_name": "Ci Test",
                    "itask_finished_by_user_id": null,
                    "itask_assesment_role_id": null,
                    "itask_assesment_hierarchy": "G",
                    "itask_assesment_method": "T",
                    "itask_assesment_user_id": null,
                    "itask_assesment_user": " ",
                    "itask_petri_net_input": 1,
                    "itask_due_offset": null,
                    "itask_duration": null,
                    "itask_sufficient_end": "N",
                    "itask_disc_flag": "N",
                    "itask_duty": "Y",
                    "iproc_name": "edit",
                    "iproc_priority": "M",
                    "tproc_name": "RB - test proměnných",
                    "iproc_owner_full_name": "Ci Test",
                    "iproc_status": "A",
                    "c_solve": 1,
                    "c_take": 0,
                    "c_handover": 1,
                    "c_add": 1,
                    "c_due": 0,
                    "itask_type": "S",
                    "itask_multiinstance_flag": "N",
                    "itask_comment": null,
                    "id": 2999644,
                    "meta": {
                        "href": "/tasks/2999644"
                    }
                }
            ]
        }
 
### Tasks With Special Condition [GET /tasks/{+type}]

    + Parameters
        + type (mine|to-assign|to-assign-dues|to-pull|done)

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/tasks" },
            "completed_in": 0.21,
            "previous": null,
            "next": { "meta": { "href": "/tasks?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "itask_name": "Example of task",
                    "iproc_name": "Case nr.1",
                    "iproc_owner_full_name": "Tomáš Jirsa",
                    "solver_user_full_name": "Tomáš Jirsa",
                    "iproc_owner_user_id": "122",
                    "itask_actual_date_start": "2015-09-01T12:44:03Z",
                    "itask_due_date_finish": "2015-09-11T10:44:03Z",
                    "itask_comment": "just a dummy comment",
                    "meta": { "href": "/task/1211" }
                }
            ]
        }
        
## Get Task [GET /tasks/{taskId}]

+ Response 200 (application/json; charset=utf-8)

        {
            "id": 2999644,
            "itask_status": "A",
            "iproc_id": 96152,
            "ttask_id": 3217,
            "itask_name": "Clever name of the task",
            "itask_is_iproc_id": null,
            "itask_description": null,
            "itask_due_date_start": null,
            "itask_due_date_finish": null,
            "itask_actual_date_start": "2015-12-07T12:05:25.000Z",
            "itask_actual_date_finish": null,
            "itask_auto_start": "N",
            "itask_user_id": 14827,
            "itask_user_name": "Ci Test",
            "itask_finished_by_user_id": null,
            "itask_assesment_role_id": null,
            "itask_assesment_hierarchy": "G",
            "itask_assesment_method": "T",
            "itask_assesment_user_id": null,
            "itask_assesment_user": " ",
            "itask_petri_net_input": 1,
            "itask_due_offset": null,
            "itask_duration": null,
            "itask_sufficient_end": "N",
            "itask_disc_flag": "N",
            "itask_insctruction": "Very long instructions...",
            "itask_duty": "Y",
            "iproc_name": "edit",
            "iproc_priority": "M",
            "tproc_name": "RB - test proměnných",
            "iproc_owner_full_name": "Ci Test",
            "iproc_status": "A",
            "c_solve": 1,
            "c_take": 0,
            "c_handover": 1,
            "c_add": 1,
            "c_due": 0,
            "itask_type": "S",
            "itask_multiinstance_flag": "N",
            "itask_comment": null,
            "meta": { "href": "/task/1211" }
        }
      
## Get Tasks Summary [GET /tasks/info]

+ Response 200 (application/json; charset=utf-8)

        {
            "MY_TASKS": "100",
            "MY_TASKS_MISS": "111",
            "TO_ASSIGN": "22",
            "MY_PROCESSES": "11",
            "MY_PROCESSES_PROB": "122",
            "TO_PULL": "22"
        }

## Get Task Attachments [GET /tasks/{taskId}/attachments]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/tasks/{taskId}/attachments" },
            "completed_in": 121,
            "items": [
                {
                    "id": "1",
                    "dmsf_name": "some clever note",
                    "dmsf_insert_date": "2015-09-11T10:44:03Z",
                    "dmsf_owner_full_name": "Thomas Mann",
                    "dmsf_revision": 1,
                    "iproc_name": "Name of process",
                    "meta": { "href": "/files/1211" }
                }
            ]
        }
        
## Get Task Variables [GET /tasks/{taskId}/variables]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/task/variables/{id}" },
            "completed_in": 0.21,
            "items": [
                {
                    "id": "1",
                    "ivar_name": "Variable with text",
                    "ivar_type": "T",
                    "ivar_attribute": "A",
                    "ivar_usage": "M",
                    "ivar_value": "value of variable",
                    "ivar_group": "nameOfTheGroup",
                    "ivar_lov": [
                        {"title": "Yes", value: "Yes"},
                        {"title": "No", value: "No"}
                    ],
                    "meta": { "href": "/task/1211" }
                }
            ]
        }
       
## Get Task Variable [GET /variables/{variableId}]

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "1",
            "ivar_name": "Variable with text",
            "ivar_type": "T",
            "ivar_attribute": "A",
            "ivar_usage": "M",
            "ivar_value": "value of variable",
            "ivar_group": "nameOfTheGroup",
            "ivar_lov": [
                {"title": "Yes", value: "Yes"},
                {"title": "No", value: "No"}
            ],
            "dlist_name": "Name of dlist",
            "ivar_multi": "X",
            "meta": { "href": "/task/1211" }
        }
        
## Update Task Variables [POST /tasks/variables]

+ Request (application/json)

        {
            "items": [
                {
                    "id": "11022",
                    "ivar_name": "Name of variable",
                    "ivar_value": "Value of variable (text, number, date, ...)"
                },
                {
                    "id": "11023",
                    "ivar_value": "Value of variable (text, number, date, ...)"
                }
            ]
        }
            
+ Response 200 (application/json; charset=utf-8)

        {
            "result": true
        }
        
+ Response 400 (application/json)

        {
            "error": {"message": "Incorrect ..."}
        }

## Update Task Variable [POST /tasks/variables/{variableId}]

+ Request (application/json)

        {
            "ivar_value": "Value of variable (text, number, date, ...)"
        }
            
+ Response 200 (application/json; charset=utf-8)

        {
            "result": true
        }
        
## Retrieve Dynamic List [GET /tasks/dyn-list/{dlName}]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/tasks/dyn-list/{dlName}" },
            "completed_in": 121,
            "items": [
                {
                    "dlist_value": "some clever note"
                }
        }
        
## Task Finish [POST /tasks/finish/{taskID}]

+ Request (application/json)

        {
        }
            
+ Response 200 (application/json; charset=utf-8)

        {
            "result": true,
            "next_itask_id": 222,
            "next_itask_name": "Name of new Task"
        }


## Process [/processes]

### All Processes [GET]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/processes" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "iproc_name": "Case nr.1",
                    "tproc_name": "Template of process",
                    "folstr_name": "Folder nr.1",
                    "iproc_owner_full_name": "Thomas Mann",
                    "iproc_actual_start_date": "2015-09-01T12:44:03Z",
                    "iproc_actual_finish_date": "2015-10-11T10:44:03Z",
                    "iproc_due_date_finish": "2015-09-11T10:44:03Z",
                    "iproc_summary": "Task: Thomas Mann",
                    "meta": { "href": "/process/{id}" }
                }
            ]
        }

### Processes With Special Condition [GET /processes/{+type}]

    + Parameters
        + type (done|problem|after-due-date|suspended)
        
+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/processes/{type}" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "iproc_name": "Case nr.1",
                    "tproc_name": "Template of process",
                    "folstr_name": "Folder nr.1",
                    "iproc_owner_full_name": "122",
                    "iproc_actual_date_start": "2015-09-01T12:44:03Z",
                    "iproc_due_date_finish": "2015-09-11T10:44:03Z",
                    "iproc_summary": "Task: Thomas Mann",
                    "iproc_actual_finish_date": "2015-10-11T10:44:03Z",
                    "meta": { "href": "/process/{id}" }
                }
            ]
        }
        
## Get Process [GET /processes/{processId}]

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "Example of task",
            "tproc_name": "Name of template",
            "iproc_name": "Name of the process",
            "iproc_description": "Some description.",
            "iproc_owner_full_name": "Thomas Mann",
            "iproc_owner_orgstr_name": "Head of Marketing",
            "iproc_status": "A",
            "iproc_actual_start_date": "2015-09-11T10:44:03Z",
            "iproc_actual_finish_date" : "2015-09-11T10:44:03Z",
            "iproc_due_date_finish": "2015-09-11T10:44:03Z",
            "iproc_summary": "summary of process",
            "iproc_url": "http://alfresco.com/",
            "iproc_url_tab_name": "Alfresco"
            "meta": { "href": "/process/{id}" }
        }

## Get Process Variables [GET /processes/{processId}/variables]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "10",
            "meta": { "href" : "/process/{processId}/variables" },
            "completed_in": 11,
            "previous": null,
            "next": { "meta": { "href": "/process/{processId}/variables?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "ivar_name": "Variable with text",
                    "ivar_type": "T",
                    "ivar_attribute": "A",
                    "ivar_value": "value of variable",
                    "ivar_group": "nameOfTheGroup"
                }
            ]
        }

## Get Process Notes [GET /processes/{processId}/notes]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/process/notes/{processId}" },
            "completed_in": 0.21,
            "items": [
                {
                    "id": "1",
                    "ipn_note": "some clever note",
                    "ipn_datetime": "2015-09-11T10:44:03Z",
                    "ipn_user_full_name": "Thomas Mann",
                    "ipn_vice_user_full_name": "Thomas Mann",
                    "ipn_type": "USER",
                    "ipn_itask_name": "Name of the task"
                    "meta": { "href": "/note/1211" }
                }
            ]
        }
        
## Get Process Attachments [GET /processes/{processId}/attachments]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/process/{processId}/attachments" },
            "completed_in": 121,
            "items": [
                {
                    "id": "1",
                    "name": "some clever note",
                    "datetime_insert": "2015-09-11T10:44:03Z",
                    "dmsf_owner_full_name": "Thomas Mann",
                    "revision": 1,
                    "meta": { "href": "/process/1211" }
                }
            ]
        }

## Get Process Actual Tasks [GET /processes/{processId}/tasks]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/tasks" },
            "completed_in": 0.21,
            "previous": null,
            "next": { "meta": { "href": "/tasks?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "itask_name": "Example of task",
                    "iproc_name": "Case nr.1",
                    "iproc_owner_full_name": "Tomáš Jirsa",
                    "solver_user_full_name": "Tomáš Jirsa",
                    "iproc_owner_user_id": "122",
                    "itask_actual_date_start": "2015-09-01T12:44:03Z",
                    "itask_due_date_finish": "2015-09-11T10:44:03Z",
                    "itask_comment": "just a dummy comment",
                    "itask_status": "A",
                    "meta": { "href": "/task/1211" }
                }
            ]
        }
  
## Get Process History Tasks [GET /processes/{processId}/history]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/tasks" },
            "completed_in": 0.21,
            "previous": null,
            "next": { "meta": { "href": "/tasks?offset=20&amp;limit=10"} },
            "items": [
                {
                "org_id": 1,
                "iproc_id": 96177,
                "itask_id": 3000156,
                "itaskh_name": "Name of task",
                "itaskh_actual_date_start": "2015-12-11T14:36:59.000Z",
                "itaskh_actual_date_finish": "2015-12-11T14:36:59.000Z",
                "itaskh_due_date_start": null,
                "itaskh_due_date_finish": null,
                "itaskh_finished_by_user_id": 14847,
                "itaskh_finished_by_user": "Thomas Mann",
                "itaskh_user_id": null,
                "itaskh_note": "Task finished",
                "itaskh_subprocess_iproc_id": -1,
                "id": 1050430,
                    "meta": { "href": "/task/1211" }
                }
            ]
        }        
        
## Process Activate [POST /processes/activate/{tprocId}]

+ Request (application/json)

        {
        }
            
+ Response 200 (application/json; charset=utf-8)

        {
            "result": true,
            "next_itask_id": 222,
            "next_itask_name": "Name of new Task"
        }     

### Variable [/variables]

## Update Variable [POST /variables/{variableId}]

+ Request (application/json)

        {
            "ivar_value": "Value of variable (text, number, date, ...)"
        }
            
+ Response 200 (application/json; charset=utf-8)

        {
            "result": true
        }
        
## Custom Views [/custom-views]

### All Custom Views [GET]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "5",
            "meta": { "href" : "/custom-views" },
            "completed_in": 121,
            "items": [
                {
                    "id": "1",
                    "cv_name": "some clever note",
                    "tproc_name": "Template process name",
                    "cv_visibility": "P",
                    "cv_iproc_status_list": 1,
                    "meta": { "href": "/custom-view/1" }
                }
            ]
        }
        
### All Custom View Processes [GET /cv/{cv_id}]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "5",
            "meta": { "href" : "/cv" },
            "completed_in": 121,
            "items": [
                {
                    "id": "1",
                    "iproc_name": "some clever note",
                    "iproc_description": "Template process name",
                    "iproc_inst_owner_user": "P",
                    "iproc_actual_start_date": 1,
                    "iproc_due_date_finish": null,
                    "iproc_priority": "M",
                     "iproc_summary": null,
                     "variables": [
                        {
                            "value": "some value",
                            "tvar_id": "4321",
                            "ivar_id": "1234",
                            "ivar_name": "Název"
                        }
                     ],
                    "meta": { "href": "/custom-view/2489" }
                }
            ]
        }
   
### Create Custom View [POST /custom-views]

+ Request (application/json)

        {  
           "CV_NAME":"Cv name",
           "TPROC_ID":21,
           "COLUMNS":[  
              {  
                 "CVC_NAME":"COLUMN TITLE 1",
                 "ORG_ID":1,
                 "TVAR_ID":21,
                 "TVAR_NAME":"TVAR_NAME"
              },
              {  
                 "CVC_NAME":"COLUMN TITLE 2",
                 "ORG_ID":1,
                 "TVAR_ID":22,
                 "TVAR_NAME":"TVAR_NAME"
              }
           ],
           "SHARES":[  
              {  
                 "USER_ID":8495
              },
              {  
                 "USER_ID":1
              },              
              {  
                 "ORGSTR_ID":1
              },
              {  
                 "ROLE_ID":-1
              }
           ]
        }
            
+ Response 200 (application/json; charset=utf-8)

        {
            "result": true
        }  
        
## Template Process [/template-processes]

### Get Template Process [GET /template-processes/{templateId}]

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "1",
            "tproc_name": "Template of process",
            "tproc_description": "Description of process.",
            "tproc_status": "A",
            "tproc_owner_full_name": "Thomas Mann",
            "folstr_id": 12,
            "tproc_last_changed_by_user": "Thomas Mann",
            "tproc_last_changed_date": "2015-09-11T10:44:03Z",
            "meta": { "href": "/template-process/1211" }
        }

### All Template Processes [GET]
Retrieve all non-deleted template processes.

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/template-processes" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/template-processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "tproc_name": "Template of process",
                    "tproc_description": "Description of process.",
                    "tproc_status": "A",
                    "tproc_locked_by_user_id": 1,
                    "tproc_owner_user": "Thomas Mann",
                    "folstr_id": 12,
                    "tproc_last_changed_by_user_id": 1,
                    "tproc_last_changed_by_user": "Thomas Mann",
                    "tproc_last_changed_date": "2015-09-11T10:44:03Z",
                    "meta": { "href": "/template-process/1211" }
                }
            ]
        }

### All Template Processes in Folder [GET /template-processes/folder/{id}]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/template-processes/folder/{id}" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/template-processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "tproc_name": "Template of process",
                    "tproc_description": "Description of process.",
                    "tproc_status": "A",
                    "tproc_owner_full_name": "Thomas Mann",
                    "folstr_id": 12,
                    "tproc_last_changed_by_user": "Thomas Mann",
                    "tproc_last_changed_date": "2015-09-11T10:44:03Z",
                    "meta": { "href": "/template-process/1211" }
                }
            ]
        }
        
### All Template Processes Folders [GET /template-processes/folder/structure]

+ Response 200 (application/json; charset=utf-8)

        {
            "meta": { "href" : "/template-processes/folder/structure" },
            "items": [
                { 
                    "label": "CPM",
                    "id": 2
                },
                {
                    "label": "External", 
                    "id": 3
                }
            ]
        }   
        
### All Template Variables for Template Process [GET /template-processes/{templateId}/template-variables/]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/template-processes/{templateId}/template-variables/" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/template-processes/{templateId}/template-variables/?offset=20&amp;limit=10"} },
            "items": [
                {
                    "tvar_name":"Vyjádření řešitele",
                    "tvar_type":"LT",
                    "tvar_attribute":null,
                    "tvar_value":null,
                    "id":1738,
                    "meta": {
                        "href":"/template-processes/{tprocId}/template-variables/1738"
                    }
                }
            ]
        }         

### Get Template Variable for Template Process [GET /template-variables/{templateVariableId}]       
  
+ Response 200 (application/json; charset=utf-8)

        {
        
        }
  
## Template Tasks [/template-processes/{templateId}/template-tasks]

### All Template Tasks for Template Process [GET]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/template-tasks" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/template-tasks?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "ttask_name": "Name of template task",
                    "ttask_description": "Description of process.",
                    "ttask_type": "A",
                    "ttask_sufficient_end": "S",
                    "ttask_assesment_role": "Role name",
                    "ttask_assesment_org": "Org name",
                    "ttask_assesment_user": "supervizor()",
                    "ttask_assesment_hierarchy": "",
                    "ttask_assesment_method": "",
                    "ttask_duty": "",
                    "ttask_calc_count": 10,
                    "meta": { "href": "/template-task/1211" }
                }
            ]
        }  
        
### Get Template Task [GET /template-tasks/{templateTaskId}]

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "1",
            "ttask_name": "Name of template task",
            "ttask_description": "Description of process.",
            "ttask_type": "A",
            "ttask_sufficient_end": "S",
            "ttask_assesment_role": "Role name",
            "ttask_assesment_org": "Org name",
            "ttask_assesment_user": "supervizor()",
            "ttask_assesment_hierarchy": "",
            "ttask_assesment_method": "",
            "ttask_duty": "",
            "ttask_calc_count": 10,
            "meta": { "href": "/template-task/1211" }
        }  


## User [/users]

### All Users [GET]
Retrieve all non-deleted users.

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/users" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "user_status": "A",
                    "user_name": "TMANN",
                    "user_first_name": "Thomas",
                    "user_last_name": "Mann",
                    "user_email": "thomas@mann.com",
                    "meta": { "href": "/users/1211" }
                }
            ]
        }
  
### All Deleted Users [GET /users/deleted]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/users/deleted" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "user_status": "A",
                    "user_name": "TMANN",
                    "user_first_name": "Thomas",
                    "user_last_name": "Mann",
                    "user_email": "thomas@mann.com",
                    "meta": { "href": "/users/1211" }
                }
            ]
        }
        
### Users of Organization Unit [GET /users/organization/{orgstrId}]

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/users/organization/{orgstrId}" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/users/organization/{orgstrId}?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id": "1",
                    "user_status": "A",
                    "user_name": "TMANN",
                    "user_first_name": "Thomas",
                    "user_last_name": "Mann",
                    "user_email": "thomas@mann.com",
                    "meta": { "href": "/users/1211" }
                }
            ]
        }
        
### Get User [GET /users/{userId}]

+ Response 200 (application/json; charset=utf-8)

        {
            "id": 1,
            "user_email": "thomas@mann.cz",
            "user_first_name": "Thomas",
            "user_last_name": "Mann",
            "user_name": "TMANN",
            "user_status": "A",
            "roles":  [
                {
                    "role_name": "$Admin",
                    "id": -1,
                    "meta": {
                        "href": ""
                    }
                }
            ],
            "orgstr_id": 20,
            "meta": { "href": "/users/{userId}" }
        }
        

### Get Info of Logged User [GET /logged-user]

+ Response 200 (application/json; charset=utf-8)

        {
            "id": 1,
            "user_first_name": "Thomas",
            "user_last_name": "Mann",
            "user_name": "TMANN",
            "user_status": "A",
            "roles":  [
                {
                    "role_name": "$Inspector",
                    "id": -3,
                    "meta": {
                        "href": ""
                    }
                }
            ],
            "meta": { "href": "/users/{userId}" }
        }
        
### Update User [POST /users/{userId}]

+ Request (application/json)

        {
            
        }
            
+ Response 200 (application/json; charset=utf-8)

        {
            "result": true
        }
        
+ Response 400 (application/json; charset=utf-8)

        {
            "error": {"message": "Incorrect ..."}
        }
        
### Get org.structure [GET /org-structure]

+ Response 200 (application/json; charset=utf-8)

        {
            "meta": { "href" : "/org-structure" },
            "items": [
                { 
                    "label": "CPM",
                    "id": 2,
                    "manager_user_name": null,
                    "manager_user_id": null,
                    "children": []
                },
                {
                    "label": "External", 
                    "id": 3,
                    "manager_user_name": null,
                    "manager_user_id": null,
                    "children": [
                        {"label": "Teura", "id": 4, "manager_user_name": null, "manager_user_id": null}
                    ]
                },
                {
                    "label": "Head", 
                    "id": 5,
                    "manager_user_name": "Thomas Mann",
                    "manager_user_id": 22,
                    "children": [
                        {"label": "BI/DWH", "id": 6, "manager_user_name": null, "manager_user_id": null},
                        {"label": "Business processes", "id": 7, "manager_user_name": null, "manager_user_id": null},
                        {"label": "Sales", "id": 8, "manager_user_name": null, "manager_user_id": null},
                        {"label": "Testing", "id": 9, "manager_user_name": null, "manager_user_id": null},
                        {"label": "Development", "id": 10, "manager_user_name": null, "manager_user_id": null}
                    ]
                },
                {
                    "label": "Support", 
                    "id": 12,
                    "children": [
                        {"label": "Internal", "id": 13, "manager_user_name": null, "manager_user_id": null},
                        {"label": "External", "id": 14, "manager_user_name": null, "manager_user_id": null}
                    ]
                }
            ]
        }

### All org.units [GET /org-units]

+ Response 200 (application/json; charset=utf-8)

        {
            "meta": { "href" : "/org-units" },
            "items": [
                {
                    "id": 2942,
                    "orgstr_name": "Organisation name",
                    "parent_orgstr_id": 2867,
                    "manager_user_id": 2,
                    "manager_user_name": "Thomas Mann",
                    "company_ic": "26360870",
                    "organization_type": null,
                    "meta": {
                        "href": "/org-units/2942"
                    }
                }
            ]
        }

## User Vicing [/vice]
### User Vice For Logged User [GET]

+ Response 200 (application/json; charset=utf-8)

        {
            "uv_id": 1,
            "user_id": 112,
            "user_id_vice": 101,
            "uv_enabled": 1,
            "user_status": "A",
            "user_full_name": "Thomas Mann",
            "uv_from": "2016-04-01T00:00:00Z",
            "uv_to": "2016-06-01T00:00:00Z"
            "meta": { "href": "/plan/1211" }
        }
        
### Update vice [POST /vice]
+ Request 200 (application/json)

        {
          "FROM": "2016-04-30T21:59:58.000Z",
          "TO": "2016-04-30T21:59:59.000Z",
          "USER_ID_VICE": 9495,
          "USER_ID": 1,
          "UV_ENABLED": 1,
          "ALL_RIGHTS": true 
        }
        
+ Response 200 (application/json; charset=utf-8)
        
        {
            "result": true
        }          
        
### Set User Vice [POST]

+ Request 200 (application/json)

        {
            "user_id_vice": 101,
            "enabled": true,
            "from": "2016-04-01T00:00:00Z",
            "to": "2016-04-01T00:00:00Z"
        }
        
+ Response 200
        
        {
            "result": true
        }        
        
### Delete User Vice [DELETE /vice/{id}]
+ Request 200 (application/json)

        {
        }
        
+ Response 200 (application/json; charset=utf-8)
        
        {
            "result": true
        }        
        
        
## Plan [/plans]
### All Plans [GET]
        
+ Response 200 (application/json; charset=utf-8)

        {
            "meta": { "href" : "/plans" },
            "completed_in": 21,
            "items": [
                {
                    "id": 1,
                    "pln_status": "A",
                    "pln_name": "Plan name",
                    "tproc_name": "Template process name",
                    "user_full_name": "Thomas Mann",
                    "pln_repeat_offset_type": "",
                    "pln_repeat_offset": "",
                    "meta": { "href": "/plan/1211" }
                }
            ]
        }
    
## User Parameters [/user-parameters]
### Settings of Logged User [GET]       

+ Response 200 (application/json; charset=utf-8)  

        {
            "meta": { "href" : "/settings" },
            "completed_in": 21,
            "items": [
                {
                    "name": "MAIL_TOTAL",
                    "value": "Y"
                }
            ]
        }
        
### Update Settigs [POST]

+ Request 200 (application/json)

        [{
            "name": "CLIENT_LANGUAGE",
            "value": "cs"
        },
        {
            "name": "USER_FIRST_NAME",
            "value": "admin"
        },
        {
            "name": "USER_EMAIL",
            "value": "test@email.com"
        }]
        
+ Response 200
        
        {
            "result": true
        }
     
        
## Roles  [/roles]
### All Roles [GET /roles]

+ Response 200 (application/json; charset=utf-8)  

        {
            "meta": { "href" : "/roles" },
            "completed_in": 21,
            "items": [
                {
                    "id": 23,
                    "role_name": "Dashboard",
                    "role_is_deleted": "N",
                    "role_note": "Some role description",
                    "meta": {
                        "href": "/roles/23"
                    }
                }
            ]
        }
          
### Get Role [GET /roles/{roleId}]

+ Parameters
    + roleId: 82 (number, optional) - Id of a role.

+ Response 200 (application/json; charset=utf-8)

        {
            "id": 23,
            "role_name": "Dashboard",
            "role_is_deleted": "N",
            "role_note": "Some role description",
            "meta": {
                "href": "/roles/23"
            }
        }
        
### Structure of Roles [GET /roles/structure]      

+ Response 200 (application/json; charset=utf-8)  

        {
            "meta": { "href" : "/roles/structure" },
            "items":
                {
                    "FolderName": [
                        {
                            "id": 23,
                            "role_name": "Dashboard",
                            "role_is_deleted": "N",
                            "role_note": "Some role description",
                            "meta": {
                                "href": "/roles/23"
                            }
                        }
                    ]
                }
        }
        
## DMS [/dms]

### All Files [GET /dms/all]
Retrieve all files for user.

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/users" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id":8809,
                    "iproc_id":null,
                    "iproc_name":null,
                    "tproc_name":null,
                    "name":"Seznam subjektů web PK.doc",
                    "datetime_insert": "2015-10-11T10:44:03Z",
                    "revision":1,
                    "user_id_insert":1,
                    "dmsf_src":"DMS:_165/Seznam subjektu web PK.doc.1654a4890108e1f720d6969a086287e2.1.1428290129",
                    "dmsf_id_prev": null,
                    "dmsf_owner":"Admin Admin",
                    "is_deleted": "Y",
                    "is_current": "N",
                    "datetime_deleted": "2015-10-11T10:44:03Z",
                    "user_id_deleted": 1,
                    "file_type": "application/pdf",
                    "meta": { "href":"/dms/all/8809" }
                }
            ]
        }
        
### Current Files [GET /dms/current]
Retrieve current files for user.

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/users" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id":8809,
                    "iproc_id":null,
                    "iproc_name":null,
                    "tproc_name":null,
                    "name":"Seznam subjektů web PK.doc",
                    "datetime_insert": "2015-10-11T10:44:03Z",
                    "revision":1,
                    "user_id_insert":1,
                    "dmsf_src":"DMS:_165/Seznam subjektu web PK.doc.1654a4890108e1f720d6969a086287e2.1.1428290129",
                    "dmsf_id_prev": null,
                    "dmsf_owner":"Admin Admin",
                    "is_deleted": "Y",
                    "is_current": "N",
                    "datetime_deleted": "2015-10-11T10:44:03Z",
                    "user_id_deleted": 1,
                    "file_type": "application/pdf",
                    "meta": { "href":"/dms/all/8809" }
                }
            ]
        }   
        
### Deleted Files [GET /dms/deleted]
Retrieve all deleted files for user.

+ Response 200 (application/json; charset=utf-8)

        {
            "total_count": "84",
            "meta": { "href" : "/users" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id":8809,
                    "iproc_id":null,
                    "iproc_name":null,
                    "tproc_name":null,
                    "name":"Seznam subjektů web PK.doc",
                    "datetime_insert": "2015-10-11T10:44:03Z",
                    "revision":1,
                    "user_id_insert":1,
                    "dmsf_src":"DMS:_165/Seznam subjektu web PK.doc.1654a4890108e1f720d6969a086287e2.1.1428290129",
                    "dmsf_id_prev": null,
                    "dmsf_owner":"Admin Admin",
                    "is_deleted": "Y",
                    "is_current": "N",
                    "datetime_deleted": "2015-10-11T10:44:03Z",
                    "user_id_deleted": 1,
                    "file_type": "application/pdf",
                    "meta": { "href":"/dms/all/8809" }
                }
            ]
        }        
        
### Update logical tag relations [POST /dms/tags/logical]
+ Request 200 (application/json)

        {
            "logical": [
                {
                    "name": "UND",
                    "tags": [1, 28] 
                },
                {
                    "name": "xx",
                    "tags": [1, 29] 
                }
            ]
        }
        
+ Response 200 (application/json; charset=utf-8)
        
        {
            "result": true
        }  

### Update tags [POST /dms/tags]
+ Request 200 (application/json)

        {
          "DMST_ID": 1,
          "NAME": "Uživatel",
          "DESCRIPTION": null,
          "TYPE": "T",
          "DEFAULT_VALUE": "#username",
          "LIST_OF_VALUES": "[]"
        }
        
+ Response 200 (application/json; charset=utf-8)
        
        {
            "result": true
        }  
        
### Update file tags [POST /dms/file/:dmsfId/metadata]
+ Request 200 (application/json)

        [
            {
                "DMST_ID": 1,
                "DMST_VALUE": "VALENTA_3"
            },
            {
                "DMST_ID": 2,
                "DMST_VALUE": "good"
            }
        ]
        
        
+ Response 200 (application/json; charset=utf-8)
        
        {
            "result": true
        }
        
        
### Search file [POST /dms/search]
+ Request 200 (application/json)

        {
              "query": "fulltext value",
              "tags": {"26": "meta value"}  
        }
        
        
+ Response 200 (application/json; charset=utf-8)
        
        {
            "total_count": "84",
            "meta": { "href" : "/users" },
            "completed_in": 21,
            "previous": null,
            "next": { "meta": { "href": "/processes?offset=20&amp;limit=10"} },
            "items": [
                {
                    "id":8809,
                    "iproc_id":null,
                    "iproc_name":null,
                    "tproc_name":null,
                    "name":"Seznam subjektů web PK.doc",
                    "datetime_insert": "2015-10-11T10:44:03Z",
                    "revision":1,
                    "user_id_insert":1,
                    "dmsf_src":"DMS:_165/Seznam subjektu web PK.doc.1654a4890108e1f720d6969a086287e2.1.1428290129",
                    "dmsf_id_prev": null,
                    "dmsf_owner":"Admin Admin",
                    "is_deleted": "Y",
                    "is_current": "N",
                    "datetime_deleted": "2015-10-11T10:44:03Z",
                    "user_id_deleted": 1,
                    "file_type": "application/pdf",
                    "meta": { "href":"/dms/all/8809" }
                }
            ]
        }       
        
        
### Update folder [POST /dms/file]
+ Request 200 (application/json)

        {
          "FOLDER_NAME": "TEST_FOLDER",
          "PARENT_ID": 1
        }
        
+ Response 200 (application/json; charset=utf-8)
        
        {
            "result": true
        }   
       
### Delete folder [DELETE /dms/file]
+ Request 200 (application/json)

        {
          "FOLDER_ID": 1000
        }
        
+ Response 200 (application/json; charset=utf-8)
        
        {
            "result": true
        }